platform :ios,'6.0'

pod 'Reachability', '~>3.1.1'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'SBJson', '~> 4.0.1'
pod 'RDVTabBarController', '~> 1.1.3'
pod 'TTTAttributedLabel', '~> 1.9.5'
pod 'SDWebImage', '~> 3.6'
pod 'InnerBand', '~> 1.0.6'
pod 'Weibo', '~> 2.4.2'
pod 'WeChatSDK', '~> 0.0.1'
pod 'TSValidatedTextField', '~> 1.0.0'
pod 'SVProgressHUD', '~> 1.0'
pod 'CrittercismSDK'
pod 'FlurrySDK', '~> 5.0.0'
pod 'NSDate+TimeAgo'
pod 'BaiduPushSDK'